name: Code style checker

on:
  pull_request:
      branches:
        - develop
  push:
    branches:
      - 'feature/**'
      - 'bugfix/**'

jobs:
  super-lint:
    runs-on: windows-latest
    steps:
      
      - name: Super-Linter
        uses: github/super-linter@v4.7.3