name: Code style checker

on:
  push:
    branches:
      - 'feature/**'
      - 'bugfix/**'

jobs:
  super-lint:
    runs-on: ubuntu-latest
    steps:
      
      - name: Super-Linter
        uses: github/super-linter@v4.7.3