name: Code style checker

on:
  push:
    branches:
      - 'feature/**'
      - 'bugfix/**'

jobs:
  super-lint:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Super-Linter
        uses: github/super-linter@v4.7.3
        env:
          FILTER_REGEX_EXCLUDE: .*.md